namespace Test;

public enum TaskType : ushort
{
    OpenFile                = 0x01,
    GetFileSize             = 0x02,
    SetFileSize             = 0x03,
    FileExists              = 0x05,
    ReadFile                = 0x06,
    WriteFile               = 0x07,
    FlushFile               = 0x08,
    SetPriorityForFile      = 0x09,
    GetPriorityForFile      = 0x0A,
    CloseFile               = 0x0B,
    CreateFile              = 0x0C,
    DeleteFile              = 0x0D,
    RenameFile              = 0x0E,
    GetIOType               = 0x0F,
    DirectoryExists         = 0x10,
    OpenDirectory           = 0x11,
    GetDirectoryEntryCount  = 0x12,
    ReadDirectory           = 0x13,
    CloseDirectory          = 0x14,
    SetPriorityForDirectory = 0x15,
    GetPriorityForDirectory = 0x16,
    CreateDirectory         = 0x17,
    DeleteDirectory         = 0x18,
    RenameDirectory         = 0x19,

    Socket                  = 0x1A,
    Close                   = 0x1B,
    Connect                 = 0x1C,
    Bind                    = 0x1D,
    Listen                  = 0x1E,
    Accept                  = 0x1F,
    Recv                    = 0x20,
    Send                    = 0x21,
    Shutdown                = 0x22,
    Fcntl                   = 0x23,
    GetVar                  = 0x29,

    GetFileTimeStam         = 0x2B,
}
